basedir: /

# html lang
language: "en"

# main menu navigation
menu:
  welcome: welcome
  talks_speakers: talks & speakers
  schedule: schedule
  workshop: workshop
  sponsor: sponsor
  # scommentare per generare pagina
  # menu item for workshop

# workshops submenu (comment out if only one workshop: add items for multiple workshops)
workshop_submenu:
  front-end-testing: front-end testing
#  workshop_2: sample second workshop

# welcome submenu
welcome_submenu:
  about: about
  coc: code of conduct
  scholarships: scholarships
  where: where
  # delete this row to take out of the menu
  cfp: call for papers

# stylesheets loaded in the <head>
stylesheets:
- /assets/css/global.css

# scripts loaded in the end of the body / commented out to prevent errors in compiling layout.pug
scripts:
- /assets/js/menu.js
